In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../data/raw/visa_recommendation_120k_updated.csv")
df.head()

,applicant_id,age,nationality,current_residence,marital_status,dependents,education_level,occupation,work_experience_years,sponsorship_status,...,purpose_of_travel,intended_duration,travel_history,target_country,visa_category (Label),previous_visa_rejections,criminal_record_check,medical_exam_status,document_completeness_score,visa_fee_payment_status
0,C71788,24,Australia,Philippines,Single,3,High School,Farmer,8,University Admission,...,Tourism,Long-term,Previous Visa,US,Visitor,0,Clear,Passed,62,Paid
1,C67219,24,Paraguay,Chile,Single,4,PhD,Driver,30,Job Offer,...,Tourism,Long-term,Previous Visa,Australia,Visitor,2,Clear,Passed,75,Paid
2,C54067,51,Colombia,Netherlands,Married,4,High School,Chef,24,Job Offer,...,PR,Permanent,Previous Visa,US,PR,1,Clear,Passed,96,Paid
3,C07169,54,Algeria,South Korea,Divorced,1,High School,Artist,34,Job Offer,...,Study,Long-term,Clean,UK,Student,0,Clear,Passed,75,Paid
4,C29619,34,Guatemala,Ghana,Single,1,High School,Nurse,10,Job Offer,...,Work,Short-term,Previous Visa,Germany,Work,0,Clear,Passed,64,Paid

In [4]:
df.shape
df.columns
df.dtypes

applicant_id                   object
age                            object
nationality                    object
current_residence              object
marital_status                 object
dependents                     object
education_level                object
occupation                     object
work_experience_years          object
sponsorship_status             object
financial_status               object
language_proficiency           object
purpose_of_travel              object
intended_duration              object
travel_history                 object
target_country                 object
visa_category (Label)          object
previous_visa_rejections        int64
criminal_record_check          object
medical_exam_status            object
document_completeness_score     int64
visa_fee_payment_status        object
dtype: object

In [5]:
df.isnull().sum()

applicant_id                       0
age                              692
nationality                     1099
current_residence               1130
marital_status                     0
dependents                       894
education_level                    0
occupation                         0
work_experience_years            586
sponsorship_status             24582
financial_status                   0
language_proficiency           19513
purpose_of_travel                  0
intended_duration                  0
travel_history                     0
target_country                     0
visa_category (Label)           1432
previous_visa_rejections           0
criminal_record_check              0
medical_exam_status                0
document_completeness_score        0
visa_fee_payment_status            0
dtype: int64

In [6]:
df = df.drop(columns=['applicant_id'])

In [7]:
numeric_like_cols = [
    'age',
    'dependents',
    'work_experience_years',
    'intended_duration'
]

df[numeric_like_cols].head()

  age dependents work_experience_years intended_duration
0  24          3                     8         Long-term
1  24          4                    30         Long-term
2  51          4                    24         Permanent
3  54          1                    34         Long-term
4  34          1                    10        Short-term

In [8]:
for col in numeric_like_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [9]:
# Numerical columns
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

# Categorical columns
cat_cols = df.select_dtypes(include=['object']).columns
df[cat_cols] = df[cat_cols].fillna('Unknown')

In [10]:
df.isnull().sum()

age                                 0
nationality                         0
current_residence                   0
marital_status                      0
dependents                          0
education_level                     0
occupation                          0
work_experience_years               0
sponsorship_status                  0
financial_status                    0
language_proficiency                0
purpose_of_travel                   0
intended_duration              120000
travel_history                      0
target_country                      0
visa_category (Label)               0
previous_visa_rejections            0
criminal_record_check               0
medical_exam_status                 0
document_completeness_score         0
visa_fee_payment_status             0
dtype: int64

In [11]:
df.dtypes

age                            float64
nationality                     object
current_residence               object
marital_status                  object
dependents                     float64
education_level                 object
occupation                      object
work_experience_years          float64
sponsorship_status              object
financial_status                object
language_proficiency            object
purpose_of_travel               object
intended_duration              float64
travel_history                  object
target_country                  object
visa_category (Label)           object
previous_visa_rejections         int64
criminal_record_check           object
medical_exam_status             object
document_completeness_score      int64
visa_fee_payment_status         object
dtype: object

In [12]:
df[(df['age'] < 0) | (df['age'] > 100)]

,age,nationality,current_residence,marital_status,dependents,education_level,occupation,work_experience_years,sponsorship_status,financial_status,...,purpose_of_travel,intended_duration,travel_history,target_country,visa_category (Label),previous_visa_rejections,criminal_record_check,medical_exam_status,document_completeness_score,visa_fee_payment_status
32,-5.0,Japan,Sri Lanka,Single,2.0,PhD,Engineer,37.0,Job Offer,Medium,...,Study,NaN,Clean,Germany,Visitorrr,0,Clear,Passed,76,Paid
124,-5.0,Thailand,Finland,Married,0.0,Master,Nurse,20.0,Family Sponsor,High,...,Study,NaN,Clean,US,Student,0,Clear,Passed,88,Paid
152,120.0,Unknown,Poland,Single,2.0,High School,Accountant,38.0,Unknown,Low,...,Tourism,NaN,Previous Visa,Canada,Visitor,0,Minor Offense,Passed,75,Paid
179,120.0,Nepal,Turkey,Married,2.0,PhD,Engineer,20.0,Family Sponsor,Low,...,Special,NaN,Rejected,Canada,Special,0,Clear,Passed,97,Paid
387,-5.0,Argentina,Vietnam,Single,3.0,Bachelor,Engineer,9.0,Unknown,Medium,...,Work,NaN,Clean,Canada,Work,0,Clear,Failed,79,Paid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118912,-5.0,Guatemala,Nepal,Single,2.0,Bachelor,Student,20.0,University Admission,High,...,Special,NaN,Rejected,Germany,Special,0,Clear,Passed,65,Paid
118993,120.0,Mexico,Sweden,Widowed,2.0,PhD,Sales,20.0,University Admission,Medium,...,Study,NaN,Previous Visa,Canada,Student,0,Minor Offense,Passed,79,Paid
119506,-5.0,Turkey,Unknown,Divorced,1.0,PhD,Designer,20.0,Unknown,High,...,Study,NaN,Rejected,Australia,Student,1,Clear,Passed,92,Paid
119653,120.0,Unknown,Ethiopia,Married,2.0,High School,Chef,26.0,University Admission,Low,...,Special,NaN,Clean,Canada,Special,0,Minor Offense,Passed,72,Paid
119742,-5.0,Narnia,Ghana,Divorced,5.0,PhD,Driver,20.0,University Admission,Low,...,Tourism,NaN,Previous Visa,Australia,Visitor,0,Clear,Pending,79,Paid

In [13]:
valid_age_mask = (df['age'] >= 0) & (df['age'] <= 100)
median_age = df.loc[valid_age_mask, 'age'].median()

df.loc[~valid_age_mask, 'age'] = median_age

In [14]:
df[(df['age'] < 0) | (df['age'] > 100)]

Empty DataFrame
Columns: [age, nationality, current_residence, marital_status, dependents, education_level, occupation, work_experience_years, sponsorship_status, financial_status, language_proficiency, purpose_of_travel, intended_duration, travel_history, target_country, visa_category (Label), previous_visa_rejections, criminal_record_check, medical_exam_status, document_completeness_score, visa_fee_payment_status]
Index: []

[0 rows x 21 columns]

In [15]:
def fill_duration(row):
    if row['purpose_of_travel'] == 'Tourism':
        return 30
    elif row['purpose_of_travel'] == 'Business':
        return 15
    elif row['purpose_of_travel'] == 'Study':
        return 365
    elif row['purpose_of_travel'] == 'Work':
        return 730
    elif row['purpose_of_travel'] == 'Medical':
        return 60
    else:
        return 30

df['intended_duration'] = df.apply(fill_duration, axis=1)

In [16]:
df.shape
df.isnull().sum()
df.dtypes

age                            float64
nationality                     object
current_residence               object
marital_status                  object
dependents                     float64
education_level                 object
occupation                      object
work_experience_years          float64
sponsorship_status              object
financial_status                object
language_proficiency            object
purpose_of_travel               object
intended_duration                int64
travel_history                  object
target_country                  object
visa_category (Label)           object
previous_visa_rejections         int64
criminal_record_check           object
medical_exam_status             object
document_completeness_score      int64
visa_fee_payment_status         object
dtype: object

In [17]:
df.to_csv("../data/processed/visa_cleaned.csv", index=False)

In [19]:
df = pd.read_csv("../data/processed/visa_cleaned.csv")

In [20]:
sample_input = {
    'age': 26,
    'nationality': 'India',
    'current_residence': 'India',
    'marital_status': 'Single',
    'dependents': 0,
    'education_level': 'Graduate',
    'occupation': 'Engineer',
    'work_experience_years': 3,
    'sponsorship_status': 'No',
    'financial_status': 'Stable',
    'language_proficiency': 'English',
    'purpose_of_travel': 'Tourism',
    'intended_duration': 30,
    'travel_history': 'Yes',
    'target_country': 'UK',
    'visa_category (Label)': 'Tourist',
    'previous_visa_rejections': 0,
    'criminal_record_check': 'Pass',
    'medical_exam_status': 'Pass',
    'document_completeness_score': 85,
    'visa_fee_payment_status': 'Paid'
}

In [21]:
input_df = pd.DataFrame([sample_input])

In [22]:
missing_cols = set(df.columns) - set(input_df.columns)
extra_cols = set(input_df.columns) - set(df.columns)

missing_cols, extra_cols

(set(), set())

In [23]:
for col in numeric_like_cols:
    input_df[col] = pd.to_numeric(input_df[col], errors='coerce')

input_df = input_df.fillna('Unknown')

In [24]:
input_encoded = pd.get_dummies(input_df)
input_encoded = input_encoded.reindex(columns=df.columns, fill_value=0)

input_encoded

,age,nationality,current_residence,marital_status,dependents,education_level,occupation,work_experience_years,sponsorship_status,financial_status,...,purpose_of_travel,intended_duration,travel_history,target_country,visa_category (Label),previous_visa_rejections,criminal_record_check,medical_exam_status,document_completeness_score,visa_fee_payment_status
0,26,0,0,0,0,0,0,3,0,0,...,0,30,0,0,0,0,0,0,85,0